name: lott
description: Scratch Off Calculator.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 0.1.2
  intl: ^0.15.8
  firebase_core: "0.4.0+1"
  #"0.3.0+2"
  firebase_auth: "0.11.1"
  #"0.8.1+1"
  google_sign_in: "4.0.1+3"
  #"4.0.1+1"
  flutter_facebook_login: "2.0.0"
  #"1.2.0"
  cloud_firestore: "0.11.0+2"
  #0.9.0+2
  #numberpicker: ^1.0.0
  #firebase_messaging:
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 3.0.0

#flutter_icons:
#  android: true
#  ios: true
#  image_path: "assets/icon/app-icon.png"
#  adaptive_icon_background: "#FFFAFAFA"
#  adaptive_icon_foreground: "assets/icon/app-icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fluttericon.png
    - assets/fireauth_ui/btn_facebook_icon.png
    - assets/fireauth_ui/btn_google_icon.png
    - assets/storeavatars/no_image_icon.png
    - assets/storeavatars/0.png
    - assets/storeavatars/1.png
    - assets/storeavatars/2.png
    - assets/storeavatars/3.png
    - assets/storeavatars/4.png
    - assets/storeavatars/5.png
    - assets/storeavatars/6.png
    - assets/storeavatars/7.png
    - assets/storeavatars/8.png
    - assets/storeavatars/9.png
    - assets/storeavatars/10.png
    - assets/storeavatars/11.png
    - assets/storeavatars/12.png
    - assets/storeavatars/13.png
    - assets/storeavatars/14.png
    - assets/storeavatars/15.png
    - assets/storeavatars/16.png
    - assets/storeavatars/17.png
    - assets/storeavatars/18.png
    - assets/storeavatars/19.png
    - assets/storeavatars/20.png
    - assets/storeavatars/21.png
    - assets/storeavatars/22.png
    - assets/storeavatars/23.png
    - assets/storeavatars/24.png
    - assets/storeavatars/25.png
    - assets/storeavatars/26.png
    - assets/storeavatars/27.png
    - assets/storeavatars/28.png
    - assets/storeavatars/29.png
    # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #fonts:
   # - family: Oswald
    #  fonts:
     #   - asset: assets/Oswald-Bold.ttf
      #    weight: 700
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  #custom font https://github.com/google/fonts/tree/master/ofl/montserrat
  fonts:
    #- family: Raleway
    #  fonts:
    #    - asset: assets/fonts/Raleway-Regular.ttf
    #    - asset: assets/fonts/Raleway-Thin.ttf
    #      style: normal
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
          style: normal
    - family: Simplifica
      fonts:
        - asset: assets/fonts/Simplifica-Regular.ttf
          style: normal